# This is a basic workflow to help you get started with Actions

name: Super-testing-galore

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# We have many jobs
jobs:
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout
        uses: actions/checkout@v2
  
    #startup PIXI using the docker-compose up command
      - name: Build the image
        id: build-image
        run: |
          echo "Building docker image..."'
          docker-compose up > /dev/null 2>&1 
          echo "Image built... sleeping"
          sleep 30
          echo "I'm awake!"
  
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.4.0
        with:
          target: 'http://localhost:8000'
  
 
