# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout
        uses: actions/checkout@v1
  
    #startup PIXI using the docker-compose up command
      - name: Build the image
        id: build-image
        run: |
          docker-compose up & sleep 6000 
          echo 'this worked'
  #sleep 10 minutes to let PIXI start and update herself
  
#kill the docker container after tests are complete
      - name: Stop the image
        id: kill-image
        run: |
          docker-compose down



#tests go here
    tests:
      name: tests
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout
        uses: actions/checkout@v1

      #tests-go-here
      #SCA    
      - name: Snyk
        uses: snyk/actions/dotnet@master
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

         




